# Generated by Django 4.1.5 on 2023-01-22 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golfer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='golfer',
            name='handicap',
            field=models.DecimalField(decimal_places=2, default=999.99, max_digits=5),
        ),
    ]
