# Generated by Django 4.1.5 on 2023-01-25 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoleInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('par', models.PositiveSmallIntegerField()),
                ('handicap', models.PositiveSmallIntegerField()),
                ('yards', models.PositiveSmallIntegerField()),
                ('tee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holes', to='tee.tee')),
            ],
        ),
        migrations.AddConstraint(
            model_name='holeinfo',
            constraint=models.CheckConstraint(check=models.Q(('number__range', (1, 18))), name='Hole Number'),
        ),
        migrations.AddConstraint(
            model_name='holeinfo',
            constraint=models.CheckConstraint(check=models.Q(('par__range', (1, 6))), name='Par'),
        ),
        migrations.AddConstraint(
            model_name='holeinfo',
            constraint=models.CheckConstraint(check=models.Q(('handicap__range', (1, 18))), name='Handicap'),
        ),
        migrations.AddConstraint(
            model_name='holeinfo',
            constraint=models.CheckConstraint(check=models.Q(('yards__range', (1, 700))), name='Yards'),
        ),
    ]
